const QUIZ = {
  title: "COS Inter-Departmental Quiz",
  subtitle: "College of Science · KNUST 2026",
  topics: [
    "History of KNUST",
    "Maths",
    "Science",
    "Popular Locations & Offices on Campus",
    "History of COS",
    "Riddles",
  ],
  rounds: [
    {
      id: "fundamentals",
      name: "Fundamentals",
      round: 1,
      count: 24,
      type: "open",
      description: "Core knowledge across history, campus, COS, maths, and science.",
      questions: [
        {
          id: "r1q1",
          q: "What was the original name of KNUST before it became a university?",
          a: "Kumasi College of Technology (KCT)",
          topic: "History of KNUST",
        },
        {
          id: "r1q2",
          q: "In what year was the Kumasi College of Technology established by Government Ordinance?",
          a: "1951 (officially opened January 22, 1952)",
          topic: "History of KNUST",
        },
        {
          id: "r1q3",
          q: "How many students formed the first intake of the Kumasi College of Technology, and where were they transferred from?",
          a: "200 teacher training students, transferred from Achimota College",
          topic: "History of KNUST",
        },
        {
          id: "r1q4",
          q: "What is the name of the main library on the KNUST campus?",
          a: "Prempeh II Library",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r1q5",
          q: "The College of Science was originally established as the Faculty of Science. In what year?",
          a: "1961",
          topic: "History of COS",
        },
        {
          id: "r1q6",
          q: "How many colleges does KNUST currently have under its collegiate system?",
          a: "Six (6) colleges",
          topic: "History of KNUST",
        },
        {
          id: "r1q7",
          q: "Solve: If 3x + 7 = 22, what is the value of x?",
          a: "x = 5",
          topic: "Maths",
        },
        {
          id: "r1q8",
          q: "What is the official colour combination of the College of Science?",
          a: "Blue and White",
          topic: "History of COS",
        },
        {
          id: "r1q9",
          q: "Who was the first female Vice-Chancellor of KNUST?",
          a: "Professor Rita Akosua Dickson",
          topic: "History of KNUST",
        },
        {
          id: "r1q10",
          q: "Name the building where the offices of the Vice-Chancellor and other principal officers of KNUST are located.",
          a: "The Administration Block",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r1q11",
          q: "What is the sum of the interior angles of a hexagon?",
          a: "720 degrees",
          topic: "Maths",
        },
        {
          id: "r1q12",
          q: "In what year did KNUST transition from a centralized system to the collegiate system?",
          a: "2005 (statutes promulgated November 29, 2004; effective January 2005)",
          topic: "History of KNUST",
        },
        {
          id: "r1q13",
          q: "Name the two faculties under the College of Science.",
          a: "Faculty of Biosciences and Faculty of Physical and Computational Sciences",
          topic: "History of COS",
        },
        {
          id: "r1q14",
          q: "Which commission, set up after the 1948 Accra riots, recommended establishing a tertiary institution in Kumasi?",
          a: "The Watson Commission",
          topic: "History of KNUST",
        },
        {
          id: "r1q15",
          q: "Which Asantehene is credited with bringing to life the vision of a tertiary institution in Kumasi?",
          a: "Agyeman Prempeh II (building on Prempeh I's dream)",
          topic: "History of KNUST",
        },
        {
          id: "r1q16",
          q: "Name any THREE departments under the Faculty of Biosciences at the College of Science.",
          a: "Any three of: Biochemistry and Biotechnology; Environmental Sciences; Food Science and Technology; Optometry and Visual Science; Theoretical and Applied Biology",
          topic: "History of COS",
        },
        {
          id: "r1q17",
          q: "Name any THREE departments under the Faculty of Physical and Computational Sciences.",
          a: "Any three of: Chemistry; Computer Science; Mathematics; Actuarial Science; Physics; Meteorology and Climate Science (also National Centre for Mathematical Sciences)",
          topic: "History of COS",
        },
        {
          id: "r1q18",
          q: "In which year was the Department of Pharmacy established at KCT, and where were its first students transferred from?",
          a: "January 1953, transferred from the School of Pharmacy at Korle Bu Teaching Hospital",
          topic: "History of KNUST",
        },
        {
          id: "r1q19",
          q: "What is the chemical symbol for gold?",
          a: "Au",
          topic: "Science",
        },
        {
          id: "r1q20",
          q: "What is the SI unit of force?",
          a: "Newton (N)",
          topic: "Science",
        },
        {
          id: "r1q21",
          q: "What is the value of 7² − 3²?",
          a: "40",
          topic: "Maths",
        },
        {
          id: "r1q22",
          q: "What gas do plants absorb from the atmosphere during photosynthesis?",
          a: "Carbon dioxide (CO₂)",
          topic: "Science",
        },
        {
          id: "r1q23",
          q: "Who was appointed the first Vice-Chancellor of KNUST in 1961?",
          a: "Robert Patrick Baffour",
          topic: "History of KNUST",
        },
        {
          id: "r1q24",
          q: "What is the official website of the College of Science, KNUST?",
          a: "cos.knust.edu.gh",
          topic: "History of COS",
        },
      ],
    },
    {
      id: "speed",
      name: "Speed Race",
      round: 2,
      count: 16,
      type: "speed",
      description: "Quick-fire answers. Race the clock.",
      questions: [
        {
          id: "r2q1",
          q: "What is 15% of 240?",
          a: "36",
          topic: "Maths",
        },
        {
          id: "r2q2",
          q: "Name any TWO of the six halls of residence at KNUST.",
          a: "Any two of: Queen Elizabeth II, Unity, Independence, Republic, University (Katanga), Africa Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q3",
          q: "What is the nickname given to residents of University Hall?",
          a: "Katanga",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q4",
          q: "What is the next prime number after 29?",
          a: "31",
          topic: "Maths",
        },
        {
          id: "r2q5",
          q: "The KNUST campus covers approximately how many acres?",
          a: "Approximately 2,500 acres (2,512.96)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q6",
          q: "What is the square root of 196?",
          a: "14",
          topic: "Maths",
        },
        {
          id: "r2q7",
          q: "In which Ghanaian region is KNUST located?",
          a: "Ashanti Region",
          topic: "History of KNUST",
        },
        {
          id: "r2q8",
          q: "Simplify: 2³ × 3²",
          a: "72",
          topic: "Maths",
        },
        {
          id: "r2q9",
          q: "What is 12 × 11?",
          a: "132",
          topic: "Maths",
        },
        {
          id: "r2q10",
          q: "How many bones are in the adult human body?",
          a: "206",
          topic: "Science",
        },
        {
          id: "r2q11",
          q: "What is H₂O commonly known as?",
          a: "Water",
          topic: "Science",
        },
        {
          id: "r2q12",
          q: "What is 25% of 80?",
          a: "20",
          topic: "Maths",
        },
        {
          id: "r2q13",
          q: "How many faculties does the College of Science have?",
          a: "Two (2)",
          topic: "History of COS",
        },
        {
          id: "r2q14",
          q: "What is the boiling point of water at standard pressure in degrees Celsius?",
          a: "100°C",
          topic: "Science",
        },
        {
          id: "r2q15",
          q: "What is the cube of 3?",
          a: "27",
          topic: "Maths",
        },
        {
          id: "r2q16",
          q: "In which city is KNUST located?",
          a: "Kumasi",
          topic: "History of KNUST",
        },
      ],
    },
    {
      id: "truefalse",
      name: "True / False",
      round: 3,
      count: 36,
      type: "tf",
      description: "Decide true or false. Know the correction when wrong.",
      questions: [
        {
          id: "r3q1",
          q: "KNUST was the first public university to be established in Ghana.",
          a: "FALSE",
          explain: "It was the second; the University of Ghana (Legon) was first.",
          topic: "History of KNUST",
        },
        {
          id: "r3q2",
          q: "The College of Science has two faculties.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q3",
          q: "The Great Hall is where events like matriculation and graduation ceremonies are held at KNUST.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q4",
          q: "The Department of Computer Science is under the College of Engineering.",
          a: "FALSE",
          explain: "It is under the College of Science (Faculty of Physical and Computational Sciences).",
          topic: "History of COS",
        },
        {
          id: "r3q5",
          q: "The value of pi is exactly 22/7.",
          a: "FALSE",
          explain: "22/7 is an approximation; pi is irrational.",
          topic: "Maths",
        },
        {
          id: "r3q6",
          q: "Queen Elizabeth II Hall was officially opened by the Duke of Edinburgh in 1959.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q7",
          q: "The School of Engineering was established at KCT in October 1952.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q8",
          q: 'KNUST\'s motto includes "Technology for Development."',
          a: "FALSE",
          explain:
            'The motto is "Providing Leadership in Science, Technology, and Innovation."',
          topic: "History of KNUST",
        },
        {
          id: "r3q9",
          q: "The sum of angles in a triangle is 360 degrees.",
          a: "FALSE",
          explain: "It is 180 degrees.",
          topic: "Maths",
        },
        {
          id: "r3q10",
          q: "The Prempeh II Library is located at the central part of the KNUST campus, on a hill.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q11",
          q: "The College of Science was originally the Faculty of Science before the collegiate restructuring.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q12",
          q: "Focus FM, a campus radio station, is based in the Great Hall.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q13",
          q: "0 is a natural number.",
          a: "FALSE",
          explain:
            "By conventional definition, natural numbers start from 1.",
          topic: "Maths",
        },
        {
          id: "r3q14",
          q: "The Paa Joe Stadium is a major sports facility on the KNUST campus.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q15",
          q: "The Department of Optometry and Visual Science is in the College of Health Sciences.",
          a: "FALSE",
          explain: "It is in the College of Science (Faculty of Biosciences).",
          topic: "History of COS",
        },
        {
          id: "r3q16",
          q: "The Kumasi College of Technology was renamed the University of Science and Technology after the 1966 revolution before later becoming KNUST.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q17",
          q: "A prime number has exactly three factors.",
          a: "FALSE",
          explain: "A prime number has exactly two factors (1 and itself).",
          topic: "Maths",
        },
        {
          id: "r3q18",
          q: "The Commercial Area on campus houses banks, a post office, and a bookshop.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q19",
          q: "KNUST adopted the name 'Kwame Nkrumah University of Science and Technology' through Act 559 of 1998.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q20",
          q: "The Department of Mathematics is under the College of Humanities and Social Sciences.",
          a: "FALSE",
          explain: "It is under the College of Science.",
          topic: "History of COS",
        },
        {
          id: "r3q21",
          q: "All six halls of residence at KNUST are now mixed (male and female).",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q22",
          q: "The first Vice-Chancellor of KNUST was Robert Patrick Baffour.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q23",
          q: "The square of any negative number is also negative.",
          a: "FALSE",
          explain: "The square of a negative number is positive.",
          topic: "Maths",
        },
        {
          id: "r3q24",
          q: "Professor Christian Agyare is the 13th Vice-Chancellor of KNUST.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q25",
          q: "The College of Science assumed its current collegiate status after restructuring in December 2004.",
          a: "TRUE",
          explain: "Originally Faculty of Science (1961); became a college after the 2004 restructuring.",
          topic: "History of COS",
        },
        {
          id: "r3q26",
          q: "Actuarial Science is offered under the Faculty of Biosciences.",
          a: "FALSE",
          explain: "It is under the Faculty of Physical and Computational Sciences.",
          topic: "History of COS",
        },
        {
          id: "r3q27",
          q: "Professor Rita Akosua Dickson became KNUST's first female Vice-Chancellor on August 1, 2020.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q28",
          q: "The School of Architecture, Town Planning and Building was established at KCT in 1957.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q29",
          q: "Electrons are positively charged particles.",
          a: "FALSE",
          explain: "Electrons are negatively charged; protons are positive.",
          topic: "Science",
        },
        {
          id: "r3q30",
          q: "The speed of light is faster than the speed of sound.",
          a: "TRUE",
          topic: "Science",
        },
        {
          id: "r3q31",
          q: "Food Science and Technology is a department under the Faculty of Biosciences.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q32",
          q: "An isosceles triangle has all three sides equal.",
          a: "FALSE",
          explain: "An isosceles triangle has at least two sides equal; all three equal is equilateral.",
          topic: "Maths",
        },
        {
          id: "r3q33",
          q: "After Kwame Nkrumah's overthrow on 24 February 1966, the university was renamed the University of Science and Technology.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q34",
          q: "Meteorology and Climate Science is under the College of Science.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q35",
          q: "Water is an element.",
          a: "FALSE",
          explain: "Water (H₂O) is a compound made of hydrogen and oxygen.",
          topic: "Science",
        },
        {
          id: "r3q36",
          q: "The College of Science colours are blue and white.",
          a: "TRUE",
          topic: "History of COS",
        },
      ],
    },
    {
      id: "riddles",
      name: "Riddles",
      round: 4,
      count: 16,
      type: "open",
      description: "Campus clues and classic brainteasers — think sideways.",
      questions: [
        {
          id: "r4q1",
          q: "I was born from Achimota's children in 1952 and named after a king of technology. I grew up in Kumasi and was renamed after a president. What am I?",
          a: "KNUST (Kwame Nkrumah University of Science and Technology)",
          topic: "History of KNUST",
        },
        {
          id: "r4q2",
          q: "I sit on a hill at the heart of the campus. Students avoid me until exams draw near, then suddenly I become their best friend. What am I?",
          a: "The Prempeh II Library",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q3",
          q: "I am odd, but take away one letter and I become even. What am I?",
          a: "Seven (remove the 's' and it becomes 'even')",
          topic: "Riddles",
        },
        {
          id: "r4q4",
          q: "I am a hall fit for royalty — my name honours a queen, and a duke opened my doors in 1959. What am I?",
          a: "Queen Elizabeth II Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q5",
          q: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?",
          a: "A map",
          topic: "Riddles",
        },
        {
          id: "r4q6",
          q: "There are six of us on campus — mixed in gender, each with our own kitchen and dining hall. Two of us were once men-only before 2018. Who are we?",
          a: "The six Halls of Residence",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q7",
          q: "I am a number. Multiply me by myself and you get 144. Add me to myself and you get 24. What number am I?",
          a: "12",
          topic: "Maths",
        },
        {
          id: "r4q8",
          q: "What has keys but can't open locks, space but no room, and you can enter but not go outside?",
          a: "A keyboard",
          topic: "Riddles",
        },
        {
          id: "r4q9",
          q: "The more you take away from me, the bigger I get. What am I?",
          a: "A hole",
          topic: "Riddles",
        },
        {
          id: "r4q10",
          q: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?",
          a: "An echo",
          topic: "Riddles",
        },
        {
          id: "r4q11",
          q: "What comes once in a minute, twice in a moment, but never in a thousand years?",
          a: "The letter M",
          topic: "Riddles",
        },
        {
          id: "r4q12",
          q: "I am blue and white, I house biosciences and computation, and I was once only a faculty. What am I?",
          a: "The College of Science (COS)",
          topic: "History of COS",
        },
        {
          id: "r4q13",
          q: "What has a head, a tail, is brown, and has no legs?",
          a: "A penny / a coin",
          topic: "Riddles",
        },
        {
          id: "r4q14",
          q: "If you have me, you want to share me. If you share me, you don't have me. What am I?",
          a: "A secret",
          topic: "Riddles",
        },
        {
          id: "r4q15",
          q: "I am light as a feather, yet the strongest person can't hold me for more than a few minutes. What am I?",
          a: "Breath / your breath",
          topic: "Riddles",
        },
        {
          id: "r4q16",
          q: "What goes up but never comes down?",
          a: "Your age",
          topic: "Riddles",
        },
      ],
    },
  ],
};

// Live total for the UI
QUIZ.totalQuestions = QUIZ.rounds.reduce((n, r) => n + r.questions.length, 0);
