const QUIZ = {
  title: "COS Inter-Departmental Quiz",
  subtitle: "College of Science · KNUST 2026",
  topics: [
    "History of KNUST",
    "Maths",
    "Popular Locations & Offices on Campus",
    "History of COS",
  ],
  rounds: [
    {
      id: "fundamentals",
      name: "Fundamentals",
      round: 1,
      count: 12,
      type: "open",
      description: "Core knowledge across history, campus, COS, and maths.",
      questions: [
        {
          id: "r1q1",
          q: "What was the original name of KNUST before it became a university?",
          a: "Kumasi College of Technology (KCT)",
          topic: "History of KNUST",
        },
        {
          id: "r1q2",
          q: "In what year was the Kumasi College of Technology established by Government Ordinance?",
          a: "1951 (officially opened January 22, 1952)",
          topic: "History of KNUST",
        },
        {
          id: "r1q3",
          q: "How many students formed the first intake of the Kumasi College of Technology, and where were they transferred from?",
          a: "200 teacher training students, transferred from Achimota College",
          topic: "History of KNUST",
        },
        {
          id: "r1q4",
          q: "What is the name of the main library on the KNUST campus?",
          a: "Prempeh II Library",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r1q5",
          q: "The College of Science was originally established as the Faculty of Science. In what year?",
          a: "1961",
          topic: "History of COS",
        },
        {
          id: "r1q6",
          q: "How many colleges does KNUST currently have under its collegiate system?",
          a: "Six (6) colleges",
          topic: "History of KNUST",
        },
        {
          id: "r1q7",
          q: "Solve: If 3x + 7 = 22, what is the value of x?",
          a: "x = 5",
          topic: "Maths",
        },
        {
          id: "r1q8",
          q: "What is the official colour combination of the College of Science?",
          a: "Blue and White",
          topic: "History of COS",
        },
        {
          id: "r1q9",
          q: "Who was the first female Vice-Chancellor of KNUST?",
          a: "Professor Rita Akosua Dickson",
          topic: "History of KNUST",
        },
        {
          id: "r1q10",
          q: "Name the building where the offices of the Vice-Chancellor and other principal officers of KNUST are located.",
          a: "The Administration Block",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r1q11",
          q: "What is the sum of the interior angles of a hexagon?",
          a: "720 degrees",
          topic: "Maths",
        },
        {
          id: "r1q12",
          q: "In what year did KNUST transition from a centralized system to the collegiate system?",
          a: "2005 (statutes promulgated November 29, 2004; effective January 2005)",
          topic: "History of KNUST",
        },
      ],
    },
    {
      id: "speed",
      name: "Speed Race",
      round: 2,
      count: 8,
      type: "speed",
      description: "Quick-fire answers. Race the clock.",
      questions: [
        {
          id: "r2q1",
          q: "What is 15% of 240?",
          a: "36",
          topic: "Maths",
        },
        {
          id: "r2q2",
          q: "Name any TWO of the six halls of residence at KNUST.",
          a: "Any two of: Queen Elizabeth II, Unity, Independence, Republic, University (Katanga), Africa Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q3",
          q: "What is the nickname given to residents of University Hall?",
          a: "Katanga",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q4",
          q: "What is the next prime number after 29?",
          a: "31",
          topic: "Maths",
        },
        {
          id: "r2q5",
          q: "The KNUST campus covers approximately how many acres?",
          a: "Approximately 2,500 acres (2,512.96)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q6",
          q: "What is the square root of 196?",
          a: "14",
          topic: "Maths",
        },
        {
          id: "r2q7",
          q: "In which Ghanaian region is KNUST located?",
          a: "Ashanti Region",
          topic: "History of KNUST",
        },
        {
          id: "r2q8",
          q: "Simplify: 2³ × 3²",
          a: "72",
          topic: "Maths",
        },
      ],
    },
    {
      id: "truefalse",
      name: "True / False",
      round: 3,
      count: 24,
      type: "tf",
      description: "Decide true or false. Know the correction when wrong.",
      questions: [
        {
          id: "r3q1",
          q: "KNUST was the first public university to be established in Ghana.",
          a: "FALSE",
          explain: "It was the second; the University of Ghana (Legon) was first.",
          topic: "History of KNUST",
        },
        {
          id: "r3q2",
          q: "The College of Science has two faculties.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q3",
          q: "The Great Hall is where events like matriculation and graduation ceremonies are held at KNUST.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q4",
          q: "The Department of Computer Science is under the College of Engineering.",
          a: "FALSE",
          explain: "It is under the College of Science.",
          topic: "History of COS",
        },
        {
          id: "r3q5",
          q: "The value of pi is exactly 22/7.",
          a: "FALSE",
          explain: "22/7 is an approximation; pi is irrational.",
          topic: "Maths",
        },
        {
          id: "r3q6",
          q: "Queen Elizabeth II Hall was officially opened by the Duke of Edinburgh in 1959.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q7",
          q: "The School of Engineering was established at KCT in October 1952.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q8",
          q: 'KNUST\'s motto includes "Technology for Development."',
          a: "FALSE",
          explain:
            'The motto is "Providing Leadership in Science, Technology, and Innovation."',
          topic: "History of KNUST",
        },
        {
          id: "r3q9",
          q: "The sum of angles in a triangle is 360 degrees.",
          a: "FALSE",
          explain: "It is 180 degrees.",
          topic: "Maths",
        },
        {
          id: "r3q10",
          q: "The Prempeh II Library is located at the central part of the KNUST campus, on a hill.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q11",
          q: "The College of Science was originally the Faculty of Science before the collegiate restructuring.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q12",
          q: "Focus FM, a campus radio station, is based in the Great Hall.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q13",
          q: "0 is a natural number.",
          a: "FALSE",
          explain:
            "By conventional definition, natural numbers start from 1.",
          topic: "Maths",
        },
        {
          id: "r3q14",
          q: "The Paa Joe Stadium is a major sports facility on the KNUST campus.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q15",
          q: "The Department of Optometry and Visual Science is in the College of Health Sciences.",
          a: "FALSE",
          explain: "It is in the College of Science.",
          topic: "History of COS",
        },
        {
          id: "r3q16",
          q: "The Kumasi College of Technology was renamed the University of Science and Technology after the 1966 revolution before later becoming KNUST.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q17",
          q: "A prime number has exactly three factors.",
          a: "FALSE",
          explain: "A prime number has exactly two factors (1 and itself).",
          topic: "Maths",
        },
        {
          id: "r3q18",
          q: "The Commercial Area on campus houses banks, a post office, and a bookshop.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q19",
          q: "KNUST adopted the name 'Kwame Nkrumah University of Science and Technology' through Act 559 of 1998.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q20",
          q: "The Department of Mathematics is under the College of Humanities and Social Sciences.",
          a: "FALSE",
          explain: "It is under the College of Science.",
          topic: "History of COS",
        },
        {
          id: "r3q21",
          q: "All six halls of residence at KNUST are now mixed (male and female).",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q22",
          q: "The first Vice-Chancellor of KNUST was Robert Patrick Baffour.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q23",
          q: "The square of any negative number is also negative.",
          a: "FALSE",
          explain: "The square of a negative number is positive.",
          topic: "Maths",
        },
        {
          id: "r3q24",
          q: "Professor Christian Agyare is the 13th Vice-Chancellor of KNUST.",
          a: "TRUE",
          topic: "History of KNUST",
        },
      ],
    },
    {
      id: "riddles",
      name: "Riddles",
      round: 4,
      count: 7,
      type: "open",
      description: "Think sideways. Campus clues meet classic brainteasers.",
      questions: [
        {
          id: "r4q1",
          q: "I was born from Achimota's children in 1952 and named after a king of technology. I grew up in Kumasi and was renamed after a president. What am I?",
          a: "KNUST (Kwame Nkrumah University of Science and Technology)",
          topic: "History of KNUST",
        },
        {
          id: "r4q2",
          q: "I sit on a hill at the heart of the campus. Students avoid me until exams draw near, then suddenly I become their best friend. What am I?",
          a: "The Prempeh II Library",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q3",
          q: "I am odd, but take away one letter and I become even. What am I?",
          a: "Seven (remove the 's' and it becomes 'even')",
          topic: "Riddles",
        },
        {
          id: "r4q4",
          q: "I am a hall fit for royalty — my name honours a queen, and a duke opened my doors in 1959. What am I?",
          a: "Queen Elizabeth II Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q5",
          q: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?",
          a: "A map",
          topic: "Riddles",
        },
        {
          id: "r4q6",
          q: "There are six of us on campus — mixed in gender, each with our own kitchen and dining hall. Two of us were once men-only before 2018. Who are we?",
          a: "The six Halls of Residence",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q7",
          q: "I am a number. Multiply me by myself and you get 144. Add me to myself and you get 24. What number am I?",
          a: "12",
          topic: "Maths",
        },
      ],
    },
  ],
};
