const QUIZ = {
  title: "COS Inter-Departmental Quiz",
  subtitle: "College of Science · KNUST 2026",
  topics: [
    "History of KNUST",
    "Maths",
    "Science",
    "Popular Locations & Offices on Campus",
    "History of COS",
    "Riddles",
  ],
  rounds: [
    {
      id: "fundamentals",
      name: "Fundamentals",
      round: 1,
      count: 37,
      type: "open",
      description: "Core knowledge across history, campus, COS, maths, and science.",
      questions: [
        {
          id: "r1q1",
          q: "What was the original name of KNUST before it became a university?",
          a: "Kumasi College of Technology (KCT)",
          topic: "History of KNUST",
        },
        {
          id: "r1q2",
          q: "In what year was the Kumasi College of Technology established by Government Ordinance?",
          a: "1951 (officially opened January 22, 1952)",
          topic: "History of KNUST",
        },
        {
          id: "r1q3",
          q: "How many students formed the first intake of the Kumasi College of Technology, and where were they transferred from?",
          a: "200 teacher training students, transferred from Achimota College",
          topic: "History of KNUST",
        },
        {
          id: "r1q4",
          q: "What is the name of the main library on the KNUST campus?",
          a: "Prempeh II Library",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r1q5",
          q: "The College of Science was originally established as the Faculty of Science. In what year?",
          a: "1961",
          topic: "History of COS",
        },
        {
          id: "r1q6",
          q: "How many colleges does KNUST currently have under its collegiate system?",
          a: "Six (6) colleges",
          topic: "History of KNUST",
        },
        {
          id: "r1q7",
          q: "Solve for x: 2(x − 3) + 5 = 3x − 4",
          a: "x = 5",
          topic: "Maths",
        },
        {
          id: "r1q8",
          q: "What is the official colour combination of the College of Science?",
          a: "Blue and White",
          topic: "History of COS",
        },
        {
          id: "r1q9",
          q: "Who was the first female Vice-Chancellor of KNUST?",
          a: "Professor Rita Akosua Dickson",
          topic: "History of KNUST",
        },
        {
          id: "r1q10",
          q: "Name the building where the offices of the Vice-Chancellor and other principal officers of KNUST are located.",
          a: "The Administration Block",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r1q11",
          q: "What is the sum of the interior angles of a hexagon?",
          a: "720 degrees",
          topic: "Maths",
        },
        {
          id: "r1q12",
          q: "In what year did KNUST transition from a centralized system to the collegiate system?",
          a: "2005 (statutes promulgated November 29, 2004; effective January 2005)",
          topic: "History of KNUST",
        },
        {
          id: "r1q13",
          q: "Name the two faculties under the College of Science.",
          a: "Faculty of Biosciences and Faculty of Physical and Computational Sciences",
          topic: "History of COS",
        },
        {
          id: "r1q14",
          q: "Which commission, set up after the 1948 Accra riots, recommended establishing a tertiary institution in Kumasi?",
          a: "The Watson Commission",
          topic: "History of KNUST",
        },
        {
          id: "r1q15",
          q: "Which Asantehene is credited with bringing to life the vision of a tertiary institution in Kumasi?",
          a: "Agyeman Prempeh II (building on Prempeh I's dream)",
          topic: "History of KNUST",
        },
        {
          id: "r1q16",
          q: "Name any THREE departments under the Faculty of Biosciences at the College of Science.",
          a: "Any three of: Biochemistry and Biotechnology; Environmental Sciences; Food Science and Technology; Optometry and Visual Science; Theoretical and Applied Biology",
          topic: "History of COS",
        },
        {
          id: "r1q17",
          q: "Name any THREE departments under the Faculty of Physical and Computational Sciences.",
          a: "Any three of: Chemistry; Computer Science; Mathematics; Actuarial Science; Physics; Meteorology and Climate Science (also National Centre for Mathematical Sciences)",
          topic: "History of COS",
        },
        {
          id: "r1q18",
          q: "In which year was the Department of Pharmacy established at KCT, and where were its first students transferred from?",
          a: "January 1953, transferred from the School of Pharmacy at Korle Bu Teaching Hospital",
          topic: "History of KNUST",
        },
        {
          id: "r1q19",
          q: "What is the chemical symbol for gold?",
          a: "Au",
          topic: "Science",
        },
        {
          id: "r1q20",
          q: "What is the SI unit of force?",
          a: "Newton (N)",
          topic: "Science",
        },
        {
          id: "r1q21",
          q: "Factorise: x² − 5x + 6",
          a: "(x − 2)(x − 3)",
          topic: "Maths",
        },
        {
          id: "r1q22",
          q: "What gas do plants absorb from the atmosphere during photosynthesis?",
          a: "Carbon dioxide (CO₂)",
          topic: "Science",
        },
        {
          id: "r1q23",
          q: "Who was appointed the first Vice-Chancellor of KNUST in 1961?",
          a: "Robert Patrick Baffour",
          topic: "History of KNUST",
        },
        {
          id: "r1q24",
          q: "What is the official website of the College of Science, KNUST?",
          a: "cos.knust.edu.gh",
          topic: "History of COS",
        },
        {
          id: "r1q25",
          q: "Solve the system: x + y = 7 and x − y = 1. What is x?",
          a: "x = 4",
          topic: "Maths",
        },
        {
          id: "r1q26",
          q: "Differentiate: d/dx (e^x)",
          a: "e^x",
          topic: "Maths",
        },
        {
          id: "r1q27",
          q: "What is the derivative of ln(x) with respect to x?",
          a: "1/x",
          topic: "Maths",
        },
        {
          id: "r1q28",
          q: "Expand (x + 2)(x − 5)",
          a: "x² − 3x − 10",
          topic: "Maths",
        },
        {
          id: "r1q29",
          q: "If cos θ = 1/2 and θ is acute, what is θ in degrees?",
          a: "60°",
          topic: "Maths",
        },
        {
          id: "r1q30",
          q: "What is the chemical formula for water?",
          a: "H₂O",
          topic: "Science",
        },
        {
          id: "r1q31",
          q: "What is the pH of a neutral aqueous solution at 25°C?",
          a: "7",
          topic: "Science",
        },
        {
          id: "r1q32",
          q: "Name the main auditorium used for major KNUST ceremonies.",
          a: "The Great Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r1q33",
          q: "Evaluate ∫ 4 dx from 0 to 3",
          a: "12",
          topic: "Maths",
        },
        {
          id: "r1q34",
          q: "Solve: log₁₀(1000) = ?",
          a: "3",
          topic: "Maths",
        },
        {
          id: "r1q35",
          q: "Who is the current Vice-Chancellor of KNUST (as of August 2026)?",
          a: "Professor Christian Agyare",
          topic: "History of KNUST",
        },
        {
          id: "r1q36",
          q: "Who is the CEO / chief executive of KNUST? (same office as the Vice-Chancellor)",
          a: "Professor Christian Agyare (Vice-Chancellor)",
          topic: "History of KNUST",
        },
        {
          id: "r1q37",
          q: "Professor Christian Agyare became KNUST's 13th Vice-Chancellor in which year?",
          a: "2026 (assumed office 1 August 2026)",
          topic: "History of KNUST",
        },
      ],
    },
    {
      id: "speed",
      name: "Speed Race",
      round: 2,
      count: 26,
      type: "speed",
      description: "Quick-fire answers. Race the clock.",
      questions: [
        {
          id: "r2q1",
          q: "Solve: 5x − 3 = 2x + 9",
          a: "x = 4",
          topic: "Maths",
        },
        {
          id: "r2q2",
          q: "Name any TWO of the six halls of residence at KNUST.",
          a: "Any two of: Queen Elizabeth II, Unity, Independence, Republic, University (Katanga), Africa Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q3",
          q: "What is the nickname given to residents of University Hall?",
          a: "Katanga",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q4",
          q: "What is the next prime number after 29?",
          a: "31",
          topic: "Maths",
        },
        {
          id: "r2q5",
          q: "The KNUST campus covers approximately how many acres?",
          a: "Approximately 2,500 acres (2,512.96)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r2q6",
          q: "Differentiate: d/dx (3x² − 4x + 1)",
          a: "6x − 4",
          topic: "Maths",
        },
        {
          id: "r2q7",
          q: "In which Ghanaian region is KNUST located?",
          a: "Ashanti Region",
          topic: "History of KNUST",
        },
        {
          id: "r2q8",
          q: "Evaluate ∫(2x + 3) dx (omit +C)",
          a: "x² + 3x",
          topic: "Maths",
        },
        {
          id: "r2q9",
          q: "If f(x) = x² − 2x, find f'(x)",
          a: "2x − 2",
          topic: "Maths",
        },
        {
          id: "r2q10",
          q: "How many bones are in the adult human body?",
          a: "206",
          topic: "Science",
        },
        {
          id: "r2q11",
          q: "What is H₂O commonly known as?",
          a: "Water",
          topic: "Science",
        },
        {
          id: "r2q12",
          q: "Solve the quadratic: x² − 9 = 0 (positive root)",
          a: "3",
          topic: "Maths",
        },
        {
          id: "r2q13",
          q: "How many faculties does the College of Science have?",
          a: "Two (2)",
          topic: "History of COS",
        },
        {
          id: "r2q14",
          q: "What is the boiling point of water at standard pressure in degrees Celsius?",
          a: "100°C",
          topic: "Science",
        },
        {
          id: "r2q15",
          q: "Find lim(x→0) (sin x)/x",
          a: "1",
          topic: "Maths",
        },
        {
          id: "r2q16",
          q: "In which city is KNUST located?",
          a: "Kumasi",
          topic: "History of KNUST",
        },
        {
          id: "r2q17",
          q: "Solve: 3x + 2 = 17",
          a: "x = 5",
          topic: "Maths",
        },
        {
          id: "r2q18",
          q: "d/dx (x³) = ?",
          a: "3x²",
          topic: "Maths",
        },
        {
          id: "r2q19",
          q: "∫ 5x dx (omit +C)",
          a: "(5/2)x² or 2.5x²",
          topic: "Maths",
        },
        {
          id: "r2q20",
          q: "If 2^x = 32, what is x?",
          a: "5",
          topic: "Maths",
        },
        {
          id: "r2q21",
          q: "Simplify: (a²b³)/(ab)",
          a: "ab²",
          topic: "Maths",
        },
        {
          id: "r2q22",
          q: "What is the gradient of y = 4x − 1?",
          a: "4",
          topic: "Maths",
        },
        {
          id: "r2q23",
          q: "Solve: x² = 49 (positive)",
          a: "7",
          topic: "Maths",
        },
        {
          id: "r2q24",
          q: "What is sin(90°)?",
          a: "1",
          topic: "Maths",
        },
        {
          id: "r2q25",
          q: "Atomic number of carbon?",
          a: "6",
          topic: "Science",
        },
        {
          id: "r2q26",
          q: "Approximate speed of light in vacuum (m/s)?",
          a: "3 × 10⁸",
          topic: "Science",
        },
      ],
    },
    {
      id: "truefalse",
      name: "True / False",
      round: 3,
      count: 46,
      type: "tf",
      description: "Decide true or false. Know the correction when wrong.",
      questions: [
        {
          id: "r3q1",
          q: "KNUST was the first public university to be established in Ghana.",
          a: "FALSE",
          explain: "It was the second; the University of Ghana (Legon) was first.",
          topic: "History of KNUST",
        },
        {
          id: "r3q2",
          q: "The College of Science has two faculties.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q3",
          q: "The Great Hall is where events like matriculation and graduation ceremonies are held at KNUST.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q4",
          q: "The Department of Computer Science is under the College of Engineering.",
          a: "FALSE",
          explain: "It is under the College of Science (Faculty of Physical and Computational Sciences).",
          topic: "History of COS",
        },
        {
          id: "r3q5",
          q: "The value of pi is exactly 22/7.",
          a: "FALSE",
          explain: "22/7 is an approximation; pi is irrational.",
          topic: "Maths",
        },
        {
          id: "r3q6",
          q: "Queen Elizabeth II Hall was officially opened by the Duke of Edinburgh in 1959.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q7",
          q: "The School of Engineering was established at KCT in October 1952.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q8",
          q: 'KNUST\'s motto includes "Technology for Development."',
          a: "FALSE",
          explain:
            'The motto is "Providing Leadership in Science, Technology, and Innovation."',
          topic: "History of KNUST",
        },
        {
          id: "r3q9",
          q: "The sum of angles in a triangle is 360 degrees.",
          a: "FALSE",
          explain: "It is 180 degrees.",
          topic: "Maths",
        },
        {
          id: "r3q10",
          q: "The Prempeh II Library is located at the central part of the KNUST campus, on a hill.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q11",
          q: "The College of Science was originally the Faculty of Science before the collegiate restructuring.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q12",
          q: "Focus FM, a campus radio station, is based in the Great Hall.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q13",
          q: "0 is a natural number.",
          a: "FALSE",
          explain:
            "By conventional definition, natural numbers start from 1.",
          topic: "Maths",
        },
        {
          id: "r3q14",
          q: "The Paa Joe Stadium is a major sports facility on the KNUST campus.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q15",
          q: "The Department of Optometry and Visual Science is in the College of Health Sciences.",
          a: "FALSE",
          explain: "It is in the College of Science (Faculty of Biosciences).",
          topic: "History of COS",
        },
        {
          id: "r3q16",
          q: "The Kumasi College of Technology was renamed the University of Science and Technology after the 1966 revolution before later becoming KNUST.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q17",
          q: "A prime number has exactly three factors.",
          a: "FALSE",
          explain: "A prime number has exactly two factors (1 and itself).",
          topic: "Maths",
        },
        {
          id: "r3q18",
          q: "The Commercial Area on campus houses banks, a post office, and a bookshop.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q19",
          q: "KNUST adopted the name 'Kwame Nkrumah University of Science and Technology' through Act 559 of 1998.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q20",
          q: "The Department of Mathematics is under the College of Humanities and Social Sciences.",
          a: "FALSE",
          explain: "It is under the College of Science.",
          topic: "History of COS",
        },
        {
          id: "r3q21",
          q: "All six halls of residence at KNUST are now mixed (male and female).",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q22",
          q: "The first Vice-Chancellor of KNUST was Robert Patrick Baffour.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q23",
          q: "The square of any negative number is also negative.",
          a: "FALSE",
          explain: "The square of a negative number is positive.",
          topic: "Maths",
        },
        {
          id: "r3q24",
          q: "Professor Christian Agyare is the 13th Vice-Chancellor of KNUST.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q25",
          q: "The College of Science assumed its current collegiate status after restructuring in December 2004.",
          a: "TRUE",
          explain: "Originally Faculty of Science (1961); became a college after the 2004 restructuring.",
          topic: "History of COS",
        },
        {
          id: "r3q26",
          q: "Actuarial Science is offered under the Faculty of Biosciences.",
          a: "FALSE",
          explain: "It is under the Faculty of Physical and Computational Sciences.",
          topic: "History of COS",
        },
        {
          id: "r3q27",
          q: "Professor Rita Akosua Dickson became KNUST's first female Vice-Chancellor on August 1, 2020.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q28",
          q: "The School of Architecture, Town Planning and Building was established at KCT in 1957.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q29",
          q: "Electrons are positively charged particles.",
          a: "FALSE",
          explain: "Electrons are negatively charged; protons are positive.",
          topic: "Science",
        },
        {
          id: "r3q30",
          q: "The speed of light is faster than the speed of sound.",
          a: "TRUE",
          topic: "Science",
        },
        {
          id: "r3q31",
          q: "Food Science and Technology is a department under the Faculty of Biosciences.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q32",
          q: "An isosceles triangle has all three sides equal.",
          a: "FALSE",
          explain: "An isosceles triangle has at least two sides equal; all three equal is equilateral.",
          topic: "Maths",
        },
        {
          id: "r3q33",
          q: "After Kwame Nkrumah's overthrow on 24 February 1966, the university was renamed the University of Science and Technology.",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "r3q34",
          q: "Meteorology and Climate Science is under the College of Science.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q35",
          q: "Water is an element.",
          a: "FALSE",
          explain: "Water (H₂O) is a compound made of hydrogen and oxygen.",
          topic: "Science",
        },
        {
          id: "r3q36",
          q: "The College of Science colours are blue and white.",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "r3q37",
          q: "The derivative of a constant is zero.",
          a: "TRUE",
          topic: "Maths",
        },
        {
          id: "r3q38",
          q: "∫ 2x dx = x² + C",
          a: "TRUE",
          topic: "Maths",
        },
        {
          id: "r3q39",
          q: "The quadratic formula is x = (−b ± √(b² − 4ac)) / (2a).",
          a: "TRUE",
          topic: "Maths",
        },
        {
          id: "r3q40",
          q: "lim(x→∞) 1/x = 0",
          a: "TRUE",
          topic: "Maths",
        },
        {
          id: "r3q41",
          q: "d/dx (sin x) = −cos x",
          a: "FALSE",
          explain: "d/dx (sin x) = cos x.",
          topic: "Maths",
        },
        {
          id: "r3q42",
          q: "Africa Hall is one of the six traditional halls of residence at KNUST.",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r3q43",
          q: "Photosynthesis releases oxygen as a by-product.",
          a: "TRUE",
          topic: "Science",
        },
        {
          id: "r3q44",
          q: "The College of Science has four faculties.",
          a: "FALSE",
          explain: "It has two faculties.",
          topic: "History of COS",
        },
        {
          id: "r3q45",
          q: "DNA stands for Deoxyribonucleic Acid.",
          a: "TRUE",
          topic: "Science",
        },
        {
          id: "r3q46",
          q: "A local maximum of a differentiable function can only occur where f'(x) = 0 or f' is undefined.",
          a: "TRUE",
          topic: "Maths",
        },
      ],
    },
    {
      id: "riddles",
      name: "Riddles",
      round: 4,
      count: 26,
      type: "open",
      description: "Campus clues and classic brainteasers — think sideways.",
      questions: [
        {
          id: "r4q1",
          q: "I was born from Achimota's children in 1952 and named after a king of technology. I grew up in Kumasi and was renamed after a president. What am I?",
          a: "KNUST (Kwame Nkrumah University of Science and Technology)",
          topic: "History of KNUST",
        },
        {
          id: "r4q2",
          q: "I sit on a hill at the heart of the campus. Students avoid me until exams draw near, then suddenly I become their best friend. What am I?",
          a: "The Prempeh II Library",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q3",
          q: "I am odd, but take away one letter and I become even. What am I?",
          a: "Seven (remove the 's' and it becomes 'even')",
          topic: "Riddles",
        },
        {
          id: "r4q4",
          q: "I am a hall fit for royalty — my name honours a queen, and a duke opened my doors in 1959. What am I?",
          a: "Queen Elizabeth II Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q5",
          q: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?",
          a: "A map",
          topic: "Riddles",
        },
        {
          id: "r4q6",
          q: "There are six of us on campus — mixed in gender, each with our own kitchen and dining hall. Two of us were once men-only before 2018. Who are we?",
          a: "The six Halls of Residence",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q7",
          q: "If dy/dx = 6x and y(0) = 2, find y when x = 1",
          a: "y = 5",
          topic: "Maths",
        },
        {
          id: "r4q8",
          q: "What has keys but can't open locks, space but no room, and you can enter but not go outside?",
          a: "A keyboard",
          topic: "Riddles",
        },
        {
          id: "r4q9",
          q: "The more you take away from me, the bigger I get. What am I?",
          a: "A hole",
          topic: "Riddles",
        },
        {
          id: "r4q10",
          q: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?",
          a: "An echo",
          topic: "Riddles",
        },
        {
          id: "r4q11",
          q: "What comes once in a minute, twice in a moment, but never in a thousand years?",
          a: "The letter M",
          topic: "Riddles",
        },
        {
          id: "r4q12",
          q: "I am blue and white, I house biosciences and computation, and I was once only a faculty. What am I?",
          a: "The College of Science (COS)",
          topic: "History of COS",
        },
        {
          id: "r4q13",
          q: "What has a head, a tail, is brown, and has no legs?",
          a: "A penny / a coin",
          topic: "Riddles",
        },
        {
          id: "r4q14",
          q: "If you have me, you want to share me. If you share me, you don't have me. What am I?",
          a: "A secret",
          topic: "Riddles",
        },
        {
          id: "r4q15",
          q: "I am light as a feather, yet the strongest person can't hold me for more than a few minutes. What am I?",
          a: "Breath / your breath",
          topic: "Riddles",
        },
        {
          id: "r4q16",
          q: "What goes up but never comes down?",
          a: "Your age",
          topic: "Riddles",
        },
        {
          id: "r4q17",
          q: "What is d/dx (x²)?",
          a: "2x",
          topic: "Maths",
        },
        {
          id: "r4q18",
          q: "I am the slope of the tangent; in calculus I am written f'(x). What am I?",
          a: "The derivative",
          topic: "Maths",
        },
        {
          id: "r4q19",
          q: "Find the area under y = 2 from x = 0 to x = 5.",
          a: "10",
          topic: "Maths",
        },
        {
          id: "r4q20",
          q: "Solve: 4x + 8 = 0",
          a: "x = −2",
          topic: "Maths",
        },
        {
          id: "r4q21",
          q: "If f(x) = 3x + 1, what is f(2)?",
          a: "7",
          topic: "Maths",
        },
        {
          id: "r4q22",
          q: "I am blue and white and I train scientists at KNUST. What college am I?",
          a: "College of Science (COS)",
          topic: "History of COS",
        },
        {
          id: "r4q23",
          q: "Students call me Katanga. Officially I am which hall?",
          a: "University Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "r4q24",
          q: "If y = x² − 4x + 1, what is dy/dx?",
          a: "2x − 4",
          topic: "Maths",
        },
        {
          id: "r4q25",
          q: "What can you catch but not throw?",
          a: "A cold",
          topic: "Riddles",
        },
        {
          id: "r4q26",
          q: "If log₂(8) = k, what is k?",
          a: "3",
          topic: "Maths",
        },
      ],
    },
    {
      id: "expand",
      name: "Extended Bank",
      round: 5,
      count: 120,
      type: "open",
      description: "Extra KNUST/COS, campus, maths (algebra & calculus), science, NSMQ-style popular quiz items, and riddles for deeper drills and official mocks.",
      questions: [
        {
          id: "e1",
          q: "Who succeeded Professor Rita Akosua Dickson as Vice-Chancellor of KNUST?",
          a: "Professor Christian Agyare",
          topic: "History of KNUST",
        },
        {
          id: "e2",
          q: "Before becoming Vice-Chancellor, Professor Christian Agyare served as Provost of which KNUST college?",
          a: "College of Health Sciences",
          topic: "History of KNUST",
        },
        {
          id: "e3",
          q: "True or clarify: At KNUST, the Vice-Chancellor is the chief executive (CEO) of the university.",
          a: "TRUE — the Vice-Chancellor is the CEO / chief executive",
          topic: "History of KNUST",
        },
        {
          id: "e4",
          q: "In what year was KNUST established as a university college by ordinance?",
          a: "1951",
          topic: "History of KNUST",
        },
        {
          id: "e5",
          q: "KNUST was renamed Kwame Nkrumah University of Science and Technology in which year?",
          a: "1961",
          topic: "History of KNUST",
        },
        {
          id: "e6",
          q: "After the 1966 overthrow of Nkrumah, KNUST was temporarily renamed what?",
          a: "University of Science and Technology (UST)",
          topic: "History of KNUST",
        },
        {
          id: "e7",
          q: "Name any TWO of KNUST's six colleges under the collegiate system.",
          a: "Any two of: College of Agriculture and Natural Resources; College of Art and Built Environment; College of Engineering; College of Health Sciences; College of Humanities and Social Sciences; College of Science",
          topic: "History of KNUST",
        },
        {
          id: "e8",
          q: "What is the approximate size of the KNUST campus in square kilometres (approx)?",
          a: "About 16 km² (campus often cited ~2,500 acres)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e9",
          q: "Which hall of residence is nicknamed Katanga?",
          a: "University Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e10",
          q: "Name the commercial area on campus popularly associated with student shopping and services near the halls.",
          a: "Commercial Area / Tech Junction area (campus commercial centre)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e11",
          q: "What does COS stand for at KNUST?",
          a: "College of Science",
          topic: "History of COS",
        },
        {
          id: "e12",
          q: "In what year did the Faculty of Science become the College of Science?",
          a: "2004/2005 (collegiate restructuring; college status from the 2004 statutes / 2005 system)",
          topic: "History of COS",
        },
        {
          id: "e13",
          q: "Name the two faculties in the College of Science.",
          a: "Faculty of Biosciences; Faculty of Physical and Computational Sciences",
          topic: "History of COS",
        },
        {
          id: "e14",
          q: "Optometry and Visual Science is under which faculty of COS?",
          a: "Faculty of Biosciences",
          topic: "History of COS",
        },
        {
          id: "e15",
          q: "Computer Science at KNUST (COS) is under which faculty?",
          a: "Faculty of Physical and Computational Sciences",
          topic: "History of COS",
        },
        {
          id: "e16",
          q: "Solve for x: 4x − 7 = 2x + 9",
          a: "x = 8",
          topic: "Maths",
        },
        {
          id: "e17",
          q: "Solve for x: 3(x + 2) = 2x + 14",
          a: "x = 8",
          topic: "Maths",
        },
        {
          id: "e18",
          q: "Factorise: x² − 9",
          a: "(x − 3)(x + 3)",
          topic: "Maths",
        },
        {
          id: "e19",
          q: "Factorise: x² + 5x + 6",
          a: "(x + 2)(x + 3)",
          topic: "Maths",
        },
        {
          id: "e20",
          q: "Expand: (2x − 1)(x + 4)",
          a: "2x² + 7x − 4",
          topic: "Maths",
        },
        {
          id: "e21",
          q: "If f(x) = 2x³ − x, find f'(x)",
          a: "6x² − 1",
          topic: "Maths",
        },
        {
          id: "e22",
          q: "Differentiate: d/dx (5x⁴)",
          a: "20x³",
          topic: "Maths",
        },
        {
          id: "e23",
          q: "Differentiate: d/dx (cos x)",
          a: "−sin x",
          topic: "Maths",
        },
        {
          id: "e24",
          q: "Evaluate ∫ 3x² dx (omit +C)",
          a: "x³",
          topic: "Maths",
        },
        {
          id: "e25",
          q: "Evaluate ∫₀¹ 2x dx",
          a: "1",
          topic: "Maths",
        },
        {
          id: "e26",
          q: "Find lim(x→2) (x² − 4)/(x − 2)",
          a: "4",
          topic: "Maths",
        },
        {
          id: "e27",
          q: "If dy/dx = 4x and y(0) = 1, find y(x)",
          a: "y = 2x² + 1",
          topic: "Maths",
        },
        {
          id: "e28",
          q: "Solve: x² − 5x + 4 = 0 (both roots)",
          a: "x = 1 or x = 4",
          topic: "Maths",
        },
        {
          id: "e29",
          q: "What is the gradient of the line 3x + 2y − 6 = 0?",
          a: "−3/2",
          topic: "Maths",
        },
        {
          id: "e30",
          q: "If log₁₀(x) = 2, what is x?",
          a: "100",
          topic: "Maths",
        },
        {
          id: "e31",
          q: "Simplify: (3² × 3⁴) / 3³",
          a: "3³ or 27",
          topic: "Maths",
        },
        {
          id: "e32",
          q: "What is sin(0°)?",
          a: "0",
          topic: "Maths",
        },
        {
          id: "e33",
          q: "What is cos(0°)?",
          a: "1",
          topic: "Maths",
        },
        {
          id: "e34",
          q: "Convert 90° to radians (in terms of π)",
          a: "π/2",
          topic: "Maths",
        },
        {
          id: "e35",
          q: "The product of roots of x² − 7x + 10 = 0 is?",
          a: "10",
          topic: "Maths",
        },
        {
          id: "e36",
          q: "What is the SI unit of electric current?",
          a: "Ampere (A)",
          topic: "Science",
        },
        {
          id: "e37",
          q: "What is the SI unit of energy?",
          a: "Joule (J)",
          topic: "Science",
        },
        {
          id: "e38",
          q: "What particle has a positive charge in the nucleus?",
          a: "Proton",
          topic: "Science",
        },
        {
          id: "e39",
          q: "What is the chemical symbol for sodium?",
          a: "Na",
          topic: "Science",
        },
        {
          id: "e40",
          q: "What is the chemical symbol for iron?",
          a: "Fe",
          topic: "Science",
        },
        {
          id: "e41",
          q: "Photosynthesis primarily occurs in which plant organelle?",
          a: "Chloroplast",
          topic: "Science",
        },
        {
          id: "e42",
          q: "What gas do humans exhale in higher concentration than they inhale?",
          a: "Carbon dioxide (CO₂)",
          topic: "Science",
        },
        {
          id: "e43",
          q: "What is the powerhouse of the cell?",
          a: "Mitochondrion / mitochondria",
          topic: "Science",
        },
        {
          id: "e44",
          q: "DNA base pairing: adenine pairs with?",
          a: "Thymine (T)",
          topic: "Science",
        },
        {
          id: "e45",
          q: "What is the approximate speed of sound in air at room temperature (m/s)?",
          a: "About 340–343 m/s",
          topic: "Science",
        },
        {
          id: "e46",
          q: "Newton's second law is often written as F = ?",
          a: "ma (force = mass × acceleration)",
          topic: "Science",
        },
        {
          id: "e47",
          q: "What is absolute zero in Celsius?",
          a: "−273.15°C (approx −273°C)",
          topic: "Science",
        },
        {
          id: "e48",
          q: "Which planet is known as the Red Planet?",
          a: "Mars",
          topic: "Science",
        },
        {
          id: "e49",
          q: "What is the most abundant gas in Earth's atmosphere?",
          a: "Nitrogen (N₂)",
          topic: "Science",
        },
        {
          id: "e50",
          q: "pH less than 7 indicates a solution is?",
          a: "Acidic",
          topic: "Science",
        },
        {
          id: "e51",
          q: "Where is the Prempeh II Library located?",
          a: "KNUST main campus (central/library area)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e52",
          q: "Name any TWO of: Queen Elizabeth II Hall, Unity Hall, Independence Hall, Republic Hall, University Hall, Africa Hall.",
          a: "Any two of those six halls",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e53",
          q: "What is the name of KNUST's main ceremonial hall?",
          a: "The Great Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e54",
          q: "Unity Hall is one of the six traditional halls — true or false?",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e55",
          q: "Independence Hall is named in relation to Ghana's independence era — true or false?",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e56",
          q: "Republic Hall is one of KNUST's halls of residence — true or false?",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e57",
          q: "Africa Hall is part of KNUST's traditional halls — true or false?",
          a: "TRUE",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e58",
          q: "Queen Elizabeth II Hall is often shortened by students as?",
          a: "Queens / Queen’s Hall",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e59",
          q: "The Administration Block houses which top university office?",
          a: "Vice-Chancellor and principal officers",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "e60",
          q: "What city hosts the main KNUST campus?",
          a: "Kumasi",
          topic: "History of KNUST",
        },
        {
          id: "e61",
          q: "KNUST is in which region of Ghana?",
          a: "Ashanti Region",
          topic: "History of KNUST",
        },
        {
          id: "e62",
          q: "What year did the collegiate system effectively begin at KNUST?",
          a: "2005",
          topic: "History of KNUST",
        },
        {
          id: "e63",
          q: "Who was the first female Vice-Chancellor of KNUST?",
          a: "Professor Rita Akosua Dickson",
          topic: "History of KNUST",
        },
        {
          id: "e64",
          q: "Robert Patrick Baffour was the first what of KNUST?",
          a: "Vice-Chancellor",
          topic: "History of KNUST",
        },
        {
          id: "e65",
          q: "The Watson Commission is linked to recommending a university college in Kumasi — true or false?",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "e66",
          q: "Achimota College transferred teacher-training students to early KCT — true or false?",
          a: "TRUE",
          topic: "History of KNUST",
        },
        {
          id: "e67",
          q: "Solve: 2x + 3 = 11",
          a: "x = 4",
          topic: "Maths",
        },
        {
          id: "e68",
          q: "d/dx (e^{2x}) = ?",
          a: "2e^{2x}",
          topic: "Maths",
        },
        {
          id: "e69",
          q: "∫ (1/x) dx (omit +C, x > 0)",
          a: "ln x (or ln|x|)",
          topic: "Maths",
        },
        {
          id: "e70",
          q: "If 5ˣ = 125, x = ?",
          a: "3",
          topic: "Maths",
        },
        {
          id: "e71",
          q: "The sum of interior angles of a triangle is?",
          a: "180°",
          topic: "Maths",
        },
        {
          id: "e72",
          q: "Area of a circle formula?",
          a: "πr²",
          topic: "Maths",
        },
        {
          id: "e73",
          q: "Pythagoras: in a right triangle, a² + b² = ?",
          a: "c² (hypotenuse squared)",
          topic: "Maths",
        },
        {
          id: "e74",
          q: "Derivative of a constant k is?",
          a: "0",
          topic: "Maths",
        },
        {
          id: "e75",
          q: "∫₀² x dx = ?",
          a: "2",
          topic: "Maths",
        },
        {
          id: "e76",
          q: "What has hands but cannot clap?",
          a: "A clock",
          topic: "Riddles",
        },
        {
          id: "e77",
          q: "What gets wetter the more it dries?",
          a: "A towel",
          topic: "Riddles",
        },
        {
          id: "e78",
          q: "I have branches but no fruit, trunk or leaves — what am I?",
          a: "A bank",
          topic: "Riddles",
        },
        {
          id: "e79",
          q: "Forward I am heavy, backward I am not — what word am I?",
          a: "Ton",
          topic: "Riddles",
        },
        {
          id: "e80",
          q: "What invention lets you look through a wall?",
          a: "A window",
          topic: "Riddles",
        },
        {
          id: "e81",
          q: "Biochemistry is under which COS faculty?",
          a: "Faculty of Biosciences",
          topic: "History of COS",
        },
        {
          id: "e82",
          q: "Mathematics department is under which COS faculty?",
          a: "Faculty of Physical and Computational Sciences",
          topic: "History of COS",
        },
        {
          id: "e83",
          q: "Physics is under which COS faculty?",
          a: "Faculty of Physical and Computational Sciences",
          topic: "History of COS",
        },
        {
          id: "e84",
          q: "Theoretical and Applied Biology is under Biosciences — true or false?",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "e85",
          q: "COS colours are blue and white — true or false?",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "e86",
          q: "What website domain is used by the College of Science?",
          a: "cos.knust.edu.gh",
          topic: "History of COS",
        },
        {
          id: "e87",
          q: "Food Science and Technology is a Biosciences department — true or false?",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "e88",
          q: "Environmental Science sits under Biosciences at COS — true or false?",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "e89",
          q: "Actuarial Science is under Physical and Computational Sciences — true or false?",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "e90",
          q: "Chemistry is under Physical and Computational Sciences — true or false?",
          a: "TRUE",
          topic: "History of COS",
        },
        {
          id: "e91",
          q: "Solve for y: 2y − 4 = 10",
          a: "y = 7",
          topic: "Maths",
        },
        {
          id: "e92",
          q: "If f(x) = x², f'(3) = ?",
          a: "6",
          topic: "Maths",
        },
        {
          id: "e93",
          q: "Stationary point of y = x² − 6x + 5 occurs at x = ?",
          a: "3",
          topic: "Maths",
        },
        {
          id: "e94",
          q: "∫ 6 dx from 1 to 4",
          a: "18",
          topic: "Maths",
        },
        {
          id: "e95",
          q: "Simplify √49",
          a: "7",
          topic: "Maths",
        },
        {
          id: "e96",
          q: "What is 2⁴?",
          a: "16",
          topic: "Maths",
        },
        {
          id: "e97",
          q: "Mean of 2, 4, 6, 8?",
          a: "5",
          topic: "Maths",
        },
        {
          id: "e98",
          q: "Probability of heads on a fair coin?",
          a: "1/2 or 0.5",
          topic: "Maths",
        },
        {
          id: "e99",
          q: "What element has atomic number 1?",
          a: "Hydrogen (H)",
          topic: "Science",
        },
        {
          id: "e100",
          q: "Water freezes at what temperature °C at standard pressure?",
          a: "0°C",
          topic: "Science",
        },
        {
          id: "e101",
          q: "What is the chemical formula for common table salt?",
          a: "NaCl",
          topic: "Science",
        },
        {
          id: "e102",
          q: "State Ohm's law in equation form.",
          a: "V = IR (voltage = current × resistance)",
          topic: "Science",
        },
        {
          id: "e103",
          q: "What is the approximate acceleration due to gravity on Earth (m/s²)?",
          a: "9.8 m/s² (often taken as 10 m/s²)",
          topic: "Science",
        },
        {
          id: "e104",
          q: "What is Avogadro's number (approx)?",
          a: "6.02 × 10²³",
          topic: "Science",
        },
        {
          id: "e105",
          q: "Write the formula for kinetic energy.",
          a: "½mv² (or KE = ½mv²)",
          topic: "Science",
        },
        {
          id: "e106",
          q: "What is the SI unit of power?",
          a: "Watt (W)",
          topic: "Science",
        },
        {
          id: "e107",
          q: "What is the atomic number of oxygen?",
          a: "8",
          topic: "Science",
        },
        {
          id: "e108",
          q: "Boyle's law relates which two quantities of a gas (at constant temperature)?",
          a: "Pressure and volume (P ∝ 1/V)",
          topic: "Science",
        },
        {
          id: "e109",
          q: "Which vitamin is produced in human skin when exposed to sunlight?",
          a: "Vitamin D",
          topic: "Science",
        },
        {
          id: "e110",
          q: "What is the standard frequency of AC mains electricity in Ghana?",
          a: "50 Hz",
          topic: "Science",
        },
        {
          id: "e111",
          q: "Find the LCM of 4 and 6.",
          a: "12",
          topic: "Maths",
        },
        {
          id: "e112",
          q: "Find the HCF (GCD) of 12 and 18.",
          a: "6",
          topic: "Maths",
        },
        {
          id: "e113",
          q: "What is 20% of 150?",
          a: "30",
          topic: "Maths",
        },
        {
          id: "e114",
          q: "What is the circumference of a circle in terms of radius r?",
          a: "2πr",
          topic: "Maths",
        },
        {
          id: "e115",
          q: "What is the sum of the exterior angles of any convex polygon?",
          a: "360°",
          topic: "Maths",
        },
        {
          id: "e116",
          q: "Area of a triangle with base b and height h?",
          a: "½bh",
          topic: "Maths",
        },
        {
          id: "e117",
          q: "Simplify: ¾ + ½",
          a: "5/4 or 1.25",
          topic: "Maths",
        },
        {
          id: "e118",
          q: "If a right triangle has legs 3 and 4, what is the hypotenuse?",
          a: "5",
          topic: "Maths",
        },
        {
          id: "e119",
          q: "What is π correct to two decimal places?",
          a: "3.14",
          topic: "Maths",
        },
        {
          id: "e120",
          q: "Simple interest: I = PRT/100. Find I when P = 200, R = 5%, T = 2 years.",
          a: "20",
          topic: "Maths",
        }
      ],
    },
    {
      id: "cos-complex",
      name: "COS Complex & Hall of Fame",
      round: 6,
      count: 74,
      type: "open",
      description: "Aboagye Menyeh Complex offices, leadership, directory rooms, and College Hall of Fame (from on-site signage).",
      questions: [
        {
          id: "cos1",
          q: "What is the name of the College of Science building?",
          a: "The Aboagye Menyeh Complex",
          topic: "History of COS",
        },
        {
          id: "cos2",
          q: "After whom is the College of Science building named, and what was his role?",
          a: "Prof. Aboagye Menyeh, foundation Provost of the College of Science (2004–2010)",
          topic: "History of COS",
        },
        {
          id: "cos3",
          q: "What is the College of Science motto/tagline?",
          a: "The Bedrock of Development",
          topic: "History of COS",
        },
        {
          id: "cos4",
          q: "State the Vision of the College of Science.",
          a: "To produce high calibre science graduates to support and sustain the industrial and economic development of Ghana and Africa",
          topic: "History of COS",
        },
        {
          id: "cos5",
          q: "State the Mission of the College of Science.",
          a: "To provide high quality teaching, research, entrepreneurship training and service, and to develop programmes in the pure and applied sciences for the industrial and socio-economic development of Ghana and Africa",
          topic: "History of COS",
        },
        {
          id: "cos6",
          q: "List the four core values of the College of Science.",
          a: "Excellence, Teamwork, Dedication to duty, Discipline",
          topic: "History of COS",
        },
        {
          id: "cos7",
          q: "Who is the current Provost of the College of Science?",
          a: "Prof. Philip Antwi-Agyei",
          topic: "History of COS",
        },
        {
          id: "cos8",
          q: "Who was Provost of the College of Science immediately before Prof. Philip Antwi-Agyei?",
          a: "Prof. Leonard Kofitse Amekudzi (2019–2025)",
          topic: "History of COS",
        },
        {
          id: "cos9",
          q: "Who is the Dean of the Faculty of Physical and Computational Sciences?",
          a: "Prof. Osei Akoto",
          topic: "History of COS",
        },
        {
          id: "cos10",
          q: "Who is the College of Science Counsellor?",
          a: "Mr. Rabbi Darko",
          topic: "History of COS",
        },
        {
          id: "cos11",
          q: "Who is the Examination Officer for the Department of Computer Science?",
          a: "Dr. Owusu Agyeman",
          topic: "History of COS",
        },
        {
          id: "cos12",
          q: "Which departments are located in the basement of the Aboagye Menyeh Complex?",
          a: "Optometry and Visual Science (B22) and Food Science and Technology (B15)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos13",
          q: "Which room is the Department of Optometry and Visual Science in the Aboagye Menyeh Complex?",
          a: "B22",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos14",
          q: "Which room is the Department of Food Science and Technology in the Aboagye Menyeh Complex?",
          a: "B15",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos15",
          q: "Which room is the Auditorium in the Aboagye Menyeh Complex, and what is it called?",
          a: "GF1 — the Allotey Auditorium",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos16",
          q: "Which department is on the first floor of the Aboagye Menyeh Complex?",
          a: "Computer Science (FF4)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos17",
          q: "Which two departments share the second floor of the Aboagye Menyeh Complex?",
          a: "Mathematics (SF6) and Statistics and Actuarial Science (SF24)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos18",
          q: "Which room is the Department of Statistics and Actuarial Science?",
          a: "SF24",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos19",
          q: "Name the four facilities listed on the third floor of the Aboagye Menyeh Complex.",
          a: "Office of the Provost (TF31), College Library, Conference Room, Accounts Office",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos20",
          q: "In the Aboagye Menyeh Complex, GF3 is whose office?",
          a: "Head of Department, Biochemistry and Biotechnology",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos21",
          q: "GF4 is the general office of which department?",
          a: "Biochemistry and Biotechnology",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos22",
          q: "Which laboratory is signposted at GF8–GF13?",
          a: "Oldham Laboratory",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos23",
          q: "GF14 is which laboratory?",
          a: "Food Science and Technology Laboratories (Food Analysis Laboratory)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos24",
          q: "What is GF15 in the Aboagye Menyeh Complex?",
          a: "The Staff Common Room / Tea Room",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos25",
          q: "Who is permitted to use GF15 (Staff Common Room / Tea Room)?",
          a: "Senior members only — out of bounds for students and teaching assistants",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos26",
          q: "FF4 is the general office of which department?",
          a: "Computer Science",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos27",
          q: "What instruction is posted on the FF4 (Computer Science) door?",
          a: "Please knock once and enter",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos28",
          q: "Where is the Simulation Lab located in the Aboagye Menyeh Complex?",
          a: "FF8",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos29",
          q: "SF6 is the general office / reception of which department?",
          a: "Mathematics",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos30",
          q: "Which room is the Senior Common Room in the Aboagye Menyeh Complex?",
          a: "SF25",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos31",
          q: "Which room houses the Office of the Provost and the Provost Registrar (general office / reception)?",
          a: "TF31",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos32",
          q: "Where is the College IT Office in the Aboagye Menyeh Complex?",
          a: "TF19",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos33",
          q: "What instruction is posted on the College IT Office door?",
          a: "Please knock and enter",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos34",
          q: "Which room is the Examinations Office in the Aboagye Menyeh Complex?",
          a: "TF24",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos35",
          q: "Which room is the Accounts General Office?",
          a: "TF27",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos36",
          q: "Which room is the College Accountant's office?",
          a: "TF28",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos37",
          q: "Which room is the College Counsellor's office?",
          a: "TF35",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos38",
          q: "What contact numbers are posted for the College Counsellor?",
          a: "0559540176 / 0242887536",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos39",
          q: "What is the name of the third-floor boardroom in the Aboagye Menyeh Complex?",
          a: "IbisTek Boardroom",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos40",
          q: "What are the College Library's opening hours?",
          a: "Monday to Friday, 9:00 AM – 5:00 PM",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos41",
          q: "Which office handles research funding and grant applications at the College of Science?",
          a: "Office of Grants and Research (OGR)",
          topic: "History of COS",
        },
        {
          id: "cos42",
          q: "Which Hall of Fame member from the Department of Chemistry served as Vice-Chancellor from 1992 to 1997?",
          a: "Prof. Eugene Hammond Amonoo-Neizer",
          topic: "History of KNUST",
        },
        {
          id: "cos43",
          q: "Which Vice-Chancellor (2010–2016) came from the Department of Food Science and Technology?",
          a: "Prof. William Otoo Ellis",
          topic: "History of KNUST",
        },
        {
          id: "cos44",
          q: "Which Vice-Chancellor (2016–2020) came from the Department of Theoretical and Applied Biology?",
          a: "Prof. Kwasi Obiri-Danso",
          topic: "History of KNUST",
        },
        {
          id: "cos45",
          q: "Who served as Pro Vice-Chancellor of KNUST in 1978–1979, having been Head of Mathematics and Dean of the Faculty of Science?",
          a: "Prof. Francis Kofi Ampenyin Allottey (Allotey)",
          topic: "History of KNUST",
        },
        {
          id: "cos46",
          q: "Who was the foundation Provost of the College of Science, and for what years?",
          a: "Prof. Aboagye Menyeh, 2004–2010",
          topic: "History of COS",
        },
        {
          id: "cos47",
          q: "Which Provost of the College of Science (2010–2013) came from the Department of Physics?",
          a: "Prof. Robert Kwame Nkum",
          topic: "History of COS",
        },
        {
          id: "cos48",
          q: "Who was the first female Provost of the College of Science?",
          a: "Prof. (Mrs) Ibok Nsa Oduro (2016–2019)",
          topic: "History of COS",
        },
        {
          id: "cos49",
          q: "Which Provost of the College of Science is an Atmospheric and Climate Scientist?",
          a: "Prof. Leonard Kofitse Amekudzi (2019–2025)",
          topic: "History of COS",
        },
        {
          id: "cos50",
          q: "Put these Provosts in chronological order: Amekudzi, Menyeh, Nkum, Oduro.",
          a: "Menyeh (2004–2010), Nkum (2010–2013), Oduro (2016–2019), Amekudzi (2019–2025)",
          topic: "History of COS",
        },
        {
          id: "cos51",
          q: "Who was the first Head of the Department of Physics (1963–1966)?",
          a: "Prof. Kenneth Charles Whittaker",
          topic: "History of COS",
        },
        {
          id: "cos52",
          q: "Who was a founding member of the Department of Chemistry?",
          a: "Prof. Kwesi Aggrey",
          topic: "History of COS",
        },
        {
          id: "cos53",
          q: "Who was the first female Professor in the College of Science?",
          a: "Prof. (Mrs) Victoria Pearl Dzogbefia",
          topic: "History of COS",
        },
        {
          id: "cos54",
          q: "For what was Prof. Victoria Pearl Dzogbefia awarded Distinguished University Professor?",
          a: "Being the first female Professor in the College and her contributions to Biotechnology and Biochemistry",
          topic: "History of COS",
        },
        {
          id: "cos55",
          q: "Who is Ghana's first Professor of Optometry?",
          a: "Prof. (Mrs) Angela Ofeibea Amedo",
          topic: "History of COS",
        },
        {
          id: "cos56",
          q: "Who was the longest-serving Head of the Department of Optometry and Visual Science (2008–2014)?",
          a: "Prof. (Mrs) Angela Ofeibea Amedo",
          topic: "History of COS",
        },
        {
          id: "cos57",
          q: "Who pioneered optometry in Ghana and established the training programme at KNUST?",
          a: "The late Dr. Francis Kojovi Morny",
          topic: "History of COS",
        },
        {
          id: "cos58",
          q: "Which body recognised Dr. Francis Kojovi Morny as vital to the development of optometry in Africa?",
          a: "The World Council of Optometry",
          topic: "History of COS",
        },
        {
          id: "cos59",
          q: "Which Emeritus Professor served as Head of Physics and Dean of the Faculty of Science (1993–1998)?",
          a: "Emeritus Prof. Keshaw Singh",
          topic: "History of COS",
        },
        {
          id: "cos60",
          q: "Who served as Head of the Department of Physics from 2005–2007 and again 2009–2017?",
          a: "Prof. Sylvester Kojo Danuor",
          topic: "History of COS",
        },
        {
          id: "cos61",
          q: "Which programme did Prof. Sylvester Kojo Danuor spearhead, and with which partners?",
          a: "The undergraduate degree in Meteorology and Climate Science, with the Ghana Meteorological Agency and the University of Leeds, UK",
          topic: "History of COS",
        },
        {
          id: "cos62",
          q: "Which Hall of Fame member is recognised for distinguished research in microbiology and mentorship?",
          a: "Prof. Robert Clement Abaidoo (Theoretical and Applied Biology)",
          topic: "History of COS",
        },
        {
          id: "cos63",
          q: "Which Hall of Fame member is recognised especially for administrative support in examinations?",
          a: "Prof. William Gariba Akanwariwiak (Theoretical and Applied Biology)",
          topic: "History of COS",
        },
        {
          id: "cos64",
          q: "Who was a former Director of the Institute of Distance Learning (2016–2018)?",
          a: "Prof. Isaac Kwame Dontwi",
          topic: "History of COS",
        },
        {
          id: "cos65",
          q: "Which Hall of Fame member is recognised for enzyme applications in food processing, seafood quality and food biotechnology?",
          a: "Prof. Benjamin Kofi Simpson",
          topic: "History of COS",
        },
        {
          id: "cos66",
          q: "What does HuGENE stand for?",
          a: "Human Genetics and Genomics Laboratory (Dept. of Biochemistry and Biotechnology)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos67",
          q: "When was the HuGENE Lab commissioned, and by whom?",
          a: "2 February 2023, by Prof. (Mrs) Rita Akosua Dickson, assisted by Prof. Leonard Amekudzi",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos68",
          q: "Who is the Principal Investigator of the HuGENE Lab?",
          a: "Dr. Lord Jephthah Joojo Gowans",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos69",
          q: "Name the two Multiple Principal Investigators on the HuGENE plaque.",
          a: "Dr. Solomon Obiri-Yeboah and Prof. Michael Lawrence Cunningham",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos70",
          q: "Which agency funded the HuGENE Lab?",
          a: "Fogarty International Center (FIC), National Institutes of Health",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos71",
          q: "What does COSCOMP Lab (CCL) stand for?",
          a: "College of Science Computer Laboratory",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos72",
          q: "Who funded the Simulation Laboratory?",
          a: "The World Bank and the Department of Computer Science (AFUF)",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos73",
          q: "When was the Simulation Laboratory commissioned, and by whom?",
          a: "Thursday, 5 October 2017, by Prof. Kwasi Obiri-Danso",
          topic: "Popular Locations & Offices on Campus",
        },
        {
          id: "cos74",
          q: "Who was Head of Computer Science when the Simulation Lab was built?",
          a: "Dr. Michael Asante",
          topic: "Popular Locations & Offices on Campus",
        }
      ],
    },
  ],
};

// Live total for the UI
QUIZ.totalQuestions = QUIZ.rounds.reduce((n, r) => n + r.questions.length, 0);
